server:
  port: 6000

spring:
  application:
    name: hero-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
    username: springuser
    password: ThePassword

  jpa:
    hibernate:
      ddl-auto: update
